name: Hello, world

on:
 workflow_dispatch:

jobs:
  HelloWorld:
    runs-on: [ windows-latest ]
    steps:
     - run: Install-Module -Name BcContainerHelper -RequiredVersion 6.0.2
    #  - run: New-BcAuthContext -includeDeviceLogin | New-ALGoAuthContext | set-Clipboard
       shell: pwsh
