name: Hello, world

on:
 workflow_dispatch:

jobs:
  HelloWorld:
    runs-on: [ windows-latest ]
    steps:
     - run: New-BcAuthContext -includeDeviceLogin | New-ALGoAuthContext | set-Clipboard
       shell: pwsh
