name: Hello, world

on:
 workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: powershell
  
env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  HelloWorld:
    runs-on: [ windows-latest ]
    steps:
     - powershell: echo Hello